### ISSUE TITLE
High Watermark (high_watermark) does not exist on fund of funds like (wf000c050m)

### ISSUE THREAD

**Issue by samohtx** [henrydatei/wikifolio-api#10]
High Watermark throws an exception on fund of funds like wf000c050m because this property is not available on fund of funds.

Best regards, Thomas

**Comment by henrydatei** [comment]
Can confirm this is an issue. Fixed it by returning `None` if high watermark "exists" in the data but is set to None. The Error is only thrown when something goes completely wrong
