### ISSUE TITLE
e.g. shares_dax does not exist on fund of funds like (wfdwppinv1). wikifolio_universes structures is different on fund of funds

### ISSUE THREAD

**Issue by samohtx** [henrydatei/wikifolio-api#12]
a lot of entries of the wikifolio_universe does not exist on fund of funds and throws exepctions.

the structure of the wikifolio_universe is different in comparison to normal wikifolios

best regards, Thomas

**Comment by henrydatei** [comment]
Yeah I see the problem. I'm now not looking for hard coded index positions but rather than for the universeIDs wikifolio provides and hope that they are unique and will always stay the same
