### ISSUE TITLE
wf.trader has been changed

### ISSUE THREAD

**Issue by samohtx** [henrydatei/wikifolio-api#14]
seems that Wikifolio is changing a lot :-(

Traceback (most recent call last):
  File "E:\Documents\_TH\Wikifolio\Python\TestWikifolio.py", line 125, in <module>
    print('Trader Name komplett:',wf.trader)
                                  ^^^^^^^^^
  File "E:\Documents\_TH\Wikifolio\Python\wikifolio.py", line 313, in trader
    return Trader(**self.rawData["props"]["pageProps"]["data"]["trader"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Trader.__init__() got an unexpected keyword argument 'firstName'

Best regards, Thomas

**Comment by henrydatei** [comment]
fixed

**Comment by samohtx** [comment]
they changed it again :-(
  File "E:\Documents\_TH\Wikifolio\Python\wikifolio.py", line 314, in trader
    return Trader(**self.rawData["props"]["pageProps"]["data"]["trader"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Trader.__init__() missing 1 required positional argument: 'fullName'

**Comment by henrydatei** [comment]
I've seen this when I fixed it the first time and wondered why they return `firstName`, `lastName` and `fullName` but now they removed the `fullName`. Fixed it
