### ISSUE TITLE
I can buy, but I cant sell

### ISSUE THREAD

**Issue by jan85141** [henrydatei/wikifolio-api#7]
Hello,
buying works nice with:
wf = Wikifolio.Wikifolio(user, passwd, wiki_id)
order = wf.buy_quote(1, isin)
it counts up to around 5...10 and opens the trade properly.
order.success is True and wikifolio shows me the trade
But selling with
order = wf.sell_quote(1, isin)
does not work
it counts endless without error message
can anyone tell me how to close the trade?

greetings

**Comment by henrydatei** [comment]
Quote Sell (and quote Buy) are always a bit problematic. I have no idea why, but it's implemented exactly the same way as in the website but on the website it's reliable. 

The best solution for you now is to use Limit Orders

**Comment by jan85141** [comment]
Thanks, with limit orders it works.
Can you tell me how I can get the ask/bid price? I didnt find a method for this.

**Comment by henrydatei** [comment]
There is no method for this. Depending on how precise you data has to be you could use Yahoo Finance and the Python Package `yfinance` or try to get the data directly from Lang & Schwarz (the exchange that Wikifolio works with).

**Comment by jan85141** [comment]
Thanks for the quick answers. It works now. I take the current price directly from wikifolio by webscraping.

**Comment by henrydatei** [comment]
If you want to share your code for getting the current price then feel free to make a pull request 😊
