### ISSUE TITLE
Error  +       html

### ISSUE THREAD

**Issue by ccontrolled** [henrydatei/wikifolio-api#8]
I get the error:
  File "wikifolio.py", line 50
    +       html = etree.fromstring(save_text)
    ^^^^^^^^^^^^
SyntaxError: cannot assign to expression here. Maybe you meant '==' instead of '='?

What can I do?

**Comment by henrydatei** [comment]
It's not your fault, it's mine. I copy-pasted some code from Github and forgot to remove the `+` in front of line 50. Fixed that now, sorry for inconvenience

**Comment by ccontrolled** [comment]
with the correction I get for
print(wf.performance_ever)
NONE
and also for 
print(wf.performance_since_emission)
result:
"NONE"

**Comment by henrydatei** [comment]
Yeah I see. Wikifolio has changed it's data structure. I'll change the required parts in the repo

**Comment by henrydatei** [comment]
I hopefully fixed everything
