### ISSUE TITLE
emission_date, index_level and risk_ever are not working anymore

### ISSUE THREAD

**Issue by samohtx** [henrydatei/wikifolio-api#9]
Hi,
emission_date and index_level are not working anymore always none

There is a typo in:

https://github.com/Property
def return_risk_ever(self) -> typing.Optional[float]:
return self._get_wikifolio_key_figure(0, 1, "otherKeyRiskIndicators")

should be:
https://github.com/Property
risk_ever(self) -> typing.Optional[float]:
return self._get_wikifolio_key_figure(0, 1, "otherKeyRiskIndicators")

Best regards

**Comment by henrydatei** [comment]
Emission_date should only return a value other than none if the wikifolio is issued. Not sure about index_level. Do you know any Wikifolio that is issued (so you can invest in it)?

**Comment by samohtx** [comment]
> Emission_date should only return a value other than none if the wikifolio is issued. Not sure about index_level. Do you know any Wikifolio that is issued (so you can invest in it)?

wf000fbt01 issued and ready for investment

same typo  in risk_five_years , risk_three_years, risk_one_year

Best regards

**Comment by henrydatei** [comment]
Thanks for providing the Wikifolio. I looked into it and indeed my Python Wrapper returns None when asked for `emission_date` and 0 for `index_level`. This data comes from Wikifolio itself and yes, even when you visit the website this data is missing. No idea what Wikifolio is doing there.

And I already fixed your typos

**Comment by samohtx** [comment]
for the wikifolio wf000fbt01 index_level and emission_date is available on my side see pictures below. 

best regards

![image](https://github.com/henrydatei/wikifolio-api/assets/101505420/8cfefcc4-ba9c-4930-80c7-a72889787d76)

![image](https://github.com/henrydatei/wikifolio-api/assets/101505420/75766bb6-cdcd-4d35-ba50-afa2eadba4b9)

**Comment by henrydatei** [comment]
Ok but then the data is not coming from the source I thought it came. I'll have a look at this later

**Comment by henrydatei** [comment]
I looked into it and found where the `emission_date` is coming from. It should be fixed now. I removed the property `index_level` because it's nowhere to find. If you need price information you can call `get_price_information()` on your Wikifolio.

**Comment by samohtx** [comment]
great. Thx for clarification.

Best regards
